# Configuración de GitHub Actions para automatizar la generación de assets
name: Update Assets Data

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Permitir ejecución manual
  workflow_dispatch:

jobs:
  update-assets:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Generate assets data
      run: |
        python3 generate_assets.py
    
    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add assets.js
        git diff --staged --quiet || git commit -m "Auto-update assets data"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}